---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /usr/bin/rsync -av --update --delete \
        --exclude '.git' \
        --exclude '.gitignore' \
        --exclude '.cpanel.yml' \
        --exclude 'README.md' \
        --exclude 'node_modules' \
        ./ $DEPLOYPATH